package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class AbstractFigureArgument_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AbstractFigureArgument_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.AbstractFigureArgument";
  }
}
