package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */


public class AWTDrawingShapeDefinition_BehaviorDescriptor extends AbstractShapeDefinition_BehaviorDescriptor {
  public AWTDrawingShapeDefinition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.AWTDrawingShapeDefinition";
  }
}
