package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class AWTShapeDefinition_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_getGeneratedClassName_7464726264118340734(SNode thisNode) {
    return SPropertyOperations.getString(thisNode, "name");
  }

  public static String call_getGenerateFqClassName_5642467428246720698(SNode thisNode) {
    return SNodeOperations.getModel(thisNode).getModelName() + "." + AWTShapeDefinition_Behavior.call_getGeneratedClassName_7464726264118340734(thisNode);
  }
}
