package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public class AWTShapeDefinition_BehaviorDescriptor extends AbstractShapeDefinition_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public AWTShapeDefinition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.AWTShapeDefinition";
  }
}
