package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;

public class BLDeleteHandler_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor implements IDeleteHandler_BehaviorDescriptor {
  public BLDeleteHandler_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.BLDeleteHandler";
  }
}
