package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.EditorCellModel_BehaviorDescriptor;

public class CellModel_DiagramContent_BehaviorDescriptor extends EditorCellModel_BehaviorDescriptor {
  public CellModel_DiagramContent_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.CellModel_DiagramContent";
  }
}
