package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.EditorCellModel_BehaviorDescriptor;

public class CellModel_DiagramPort_BehaviorDescriptor extends EditorCellModel_BehaviorDescriptor implements PortDeclaration_BehaviorDescriptor {
  public CellModel_DiagramPort_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.CellModel_DiagramPort";
  }
}
