package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class CellModel_DiagramNode_Behavior {
  public static void init(SNode thisNode) {
  }
}
