package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ChildRolePaletteSource_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IPaletteSource_BehaviorDescriptor {
  public ChildRolePaletteSource_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.ChildRolePaletteSource";
  }
}
