package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ConditionalEndpointTarget_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IEndpointTarget_BehaviorDescriptor {
  public ConditionalEndpointTarget_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.ConditionalEndpointTarget";
  }
}
