package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ConnectionEndpoint_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ConnectionEndpoint_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.ConnectionEndpoint";
  }
}
