package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Content_GenericElementQuery_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IDiagramContent_BehaviorDescriptor {
  public Content_GenericElementQuery_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Content_GenericElementQuery";
  }
}
