package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.InlineEditorComponent_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class Content_GenericElementQuery_InlineEditorComponent_BehaviorDescriptor extends InlineEditorComponent_BehaviorDescriptor {
  public Content_GenericElementQuery_InlineEditorComponent_BehaviorDescriptor() {
  }

  public SNode virtual_getConceptDeclaration_7055725856388417603(SNode thisNode) {
    return Content_GenericElementQuery_InlineEditorComponent_Behavior.virtual_getConceptDeclaration_7055725856388417603(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Content_GenericElementQuery_InlineEditorComponent";
  }
}
