package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */


public class Content_GenericEdgeQuery_BehaviorDescriptor extends Content_GenericElementQuery_BehaviorDescriptor implements IDiagramContent_BehaviorDescriptor {
  public Content_GenericEdgeQuery_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Content_GenericEdgeQuery";
  }
}
