package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class Content_GenericElementQuery_Query_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor {
  public Content_GenericElementQuery_Query_BehaviorDescriptor() {
  }

  public SNode virtual_getExpectedReturnType_1213877374441(SNode thisNode) {
    return Content_GenericElementQuery_Query_Behavior.virtual_getExpectedReturnType_1213877374441(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Content_GenericElementQuery_Query";
  }
}
