package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Content_Childs_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IDiagramContent_BehaviorDescriptor {
  public Content_Childs_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Content_Childs";
  }
}
