package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeChecker;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.typesystem.runtime.HUtil;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class Content_GenericElementQuery_InlineEditorComponent_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getConceptDeclaration_7055725856388417603(SNode thisNode) {
    SNode type = TypeChecker.getInstance().getRuntimeSupport().coerce_(SLinkOperations.getTarget(SNodeOperations.getAncestor(thisNode, "jetbrains.mps.editor.diagram.structure.Content_GenericElementQuery", false, false), "parameterType", true), HUtil.createMatchingPatternByConceptFQName("jetbrains.mps.lang.smodel.structure.SNodeType"), false);
    if (type != null) {
      return SLinkOperations.getTarget(type, "concept", false);
    } else {
      return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SNodeOperations.getAncestor(thisNode, "jetbrains.mps.lang.editor.structure.AbstractComponent", false, false), "virtual_getConceptDeclaration_7055725856388417603", new Object[]{});
    }
  }
}
