package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import org.jetbrains.mps.openapi.language.SConcept;

public class Content_BLQuery_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor implements IDiagramContent_BehaviorDescriptor {
  public Content_BLQuery_BehaviorDescriptor() {
  }

  public SNode virtual_getExpectedReturnType_1213877374441(SNode thisNode) {
    return Content_BLQuery_Behavior.virtual_getExpectedReturnType_1213877374441(thisNode);
  }

  public List<SNode> virtual_getParameters_1213877374450(SNode thisNode) {
    return Content_BLQuery_Behavior.virtual_getParameters_1213877374450(thisNode);
  }

  public boolean virtual_showName_1262430001741498082(SConcept thisConcept) {
    return Content_BLQuery_Behavior.virtual_showName_1262430001741498082(thisConcept);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Content_BLQuery";
  }
}
