package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class Content_GenericElementQuery_ParameterObject_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Content_GenericElementQuery_ParameterObject_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Content_GenericElementQuery_ParameterObject";
  }
}
