package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;

public class DeleteHandler_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor {
  public DeleteHandler_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.DeleteHandler";
  }
}
