package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class DiagramElement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DiagramElement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.DiagramElement";
  }
}
