package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */


public class ExternalFigureReference_BehaviorDescriptor extends AbstractFigureReference_BehaviorDescriptor {
  public ExternalFigureReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.ExternalFigureReference";
  }
}
