package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */


public class ExternalPortSpecification_BehaviorDescriptor extends PortSpecification_BehaviorDescriptor {
  public ExternalPortSpecification_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.ExternalPortSpecification";
  }
}
