package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunction_BehaviorDescriptor;
import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;

public class Function_SetLabel_BehaviorDescriptor extends ConceptFunction_BehaviorDescriptor {
  public Function_SetLabel_BehaviorDescriptor() {
  }

  public List<SNode> virtual_getParameters_1213877374450(SNode thisNode) {
    return Function_SetLabel_Behavior.virtual_getParameters_1213877374450(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Function_SetLabel";
  }
}
