package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class InlineCompositeShape_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IShape_BehaviorDescriptor {
  public InlineCompositeShape_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.InlineCompositeShape";
  }
}
