package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */


public class InplacePortSpecification_BehaviorDescriptor extends PortSpecification_BehaviorDescriptor implements PortDeclaration_BehaviorDescriptor {
  public InplacePortSpecification_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.InplacePortSpecification";
  }
}
