package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.StyleClassItem_BehaviorDescriptor;

public class LineStyle_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor {
  public LineStyle_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.LineStyle";
  }
}
