package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.ColorStyleClassItem_BehaviorDescriptor;

public class LineColor_BehaviorDescriptor extends ColorStyleClassItem_BehaviorDescriptor {
  public LineColor_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.LineColor";
  }
}
