package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.StyleClassItem_BehaviorDescriptor;

public class LineWidth_BehaviorDescriptor extends StyleClassItem_BehaviorDescriptor {
  public LineWidth_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.LineWidth";
  }
}
