package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.smodel.SReference;

public class Parameter_Graphics2D_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getType_2443692612523876968(SNode thisNode) {
    return _quotation_createNode_d4r0ov_a0a0();
  }

  private static SNode _quotation_createNode_d4r0ov_a0a0() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.ClassifierType", null, null, false);
    quotedNode_1.setReference("classifier", SReference.create("classifier", quotedNode_1, facade.createModelReference("f:java_stub#6354ebe7-c22a-4a0f-ac54-50b52ab9b065#java.awt(JDK/java.awt@java_stub)"), facade.createNodeId("~Graphics2D")));
    return quotedNode_1;
  }
}
