package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunctionParameter_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class Parameter_Label_BehaviorDescriptor extends ConceptFunctionParameter_BehaviorDescriptor {
  public Parameter_Label_BehaviorDescriptor() {
  }

  public SNode virtual_getType_2443692612523876968(SNode thisNode) {
    return Parameter_Label_Behavior.virtual_getType_2443692612523876968(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Parameter_Label";
  }
}
