package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class Parameter_ValidateConnection_FromPort_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getType_2443692612523876968(SNode thisNode) {
    return SConceptOperations.createNewNode("jetbrains.mps.baseLanguage.structure.StringType", null);
  }
}
