package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Port_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IPort_BehaviorDescriptor {
  public Port_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.Port";
  }
}
