package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class PortObject_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public PortObject_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.PortObject";
  }
}
