package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class PortSpecification_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PortSpecification_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.PortSpecification";
  }
}
