package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PortQuery_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IPort_BehaviorDescriptor {
  public PortQuery_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.PortQuery";
  }
}
