package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ShapeReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IShape_BehaviorDescriptor {
  public ShapeReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.ShapeReference";
  }
}
