package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class ShapeNodeExpression_BehaviorDescriptor extends ThisNodeExpression_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public ShapeNodeExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.ShapeNodeExpression";
  }
}
