package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ConceptFunctionParameter_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class SNodeConnectionType_Param_ToNode_BehaviorDescriptor extends ConceptFunctionParameter_BehaviorDescriptor {
  public SNodeConnectionType_Param_ToNode_BehaviorDescriptor() {
  }

  public SNode virtual_getType_2443692612523876968(SNode thisNode) {
    return SNodeConnectionType_Param_ToNode_Behavior.virtual_getType_2443692612523876968(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.SNodeConnectionType_Param_ToNode";
  }
}
