package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;

public class SNodeConnectionType_CanCreate_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_showName_1262430001741498082(SAbstractConcept thisConcept) {
    return true;
  }

  public static List<SNode> virtual_getParameters_1213877374450(SNode thisNode) {
    return ListSequence.fromListAndArray(new ArrayList<SNode>(), SConceptOperations.findConceptDeclaration("jetbrains.mps.editor.diagram.structure.SNodeConnectionType_Param_FromNode"), SConceptOperations.findConceptDeclaration("jetbrains.mps.editor.diagram.structure.SNodeConnectionType_Param_FromPort"), SConceptOperations.findConceptDeclaration("jetbrains.mps.editor.diagram.structure.SNodeConnectionType_Param_ToNode"), SConceptOperations.findConceptDeclaration("jetbrains.mps.editor.diagram.structure.SNodeConnectionType_Param_ToPort"));
  }

  public static SNode virtual_getExpectedReturnType_1213877374441(SNode thisNode) {
    return _quotation_createNode_o8vvwb_a0a2();
  }

  private static SNode _quotation_createNode_o8vvwb_a0a2() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.BooleanType", null, null, false);
    return quotedNode_1;
  }
}
