package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class StandardShape_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IShape_BehaviorDescriptor, IDontSubstituteByDefault_BehaviorDescriptor {
  public StandardShape_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.StandardShape";
  }
}
