package jetbrains.mps.editor.diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class ThisNodeExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ThisNodeExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor.diagram.structure.ThisNodeExpression";
  }
}
