package jetbrains.mps.editor.diagram.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum LineStyleValues {
  SOLID("SOLID", "SOLID"),
  DASHED("DASHED", "DASHED");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<LineStyleValues> getConstants() {
    List<LineStyleValues> list = ListSequence.fromList(new LinkedList<LineStyleValues>());
    ListSequence.fromList(list).addElement(LineStyleValues.SOLID);
    ListSequence.fromList(list).addElement(LineStyleValues.DASHED);
    return list;
  }

  public static LineStyleValues getDefault() {
    return LineStyleValues.SOLID;
  }

  public static LineStyleValues parseValue(String value) {
    if (value == null) {
      return LineStyleValues.getDefault();
    }
    if (value.equals(LineStyleValues.SOLID.getValueAsString())) {
      return LineStyleValues.SOLID;
    }
    if (value.equals(LineStyleValues.DASHED.getValueAsString())) {
      return LineStyleValues.DASHED;
    }
    return LineStyleValues.getDefault();
  }

  private String myValue;

  LineStyleValues(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
