package jetbrains.mps.editor.diagram.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.intentions.IntentionExecutable;
import jetbrains.mps.intentions.IntentionType;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Collections;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.intentions.IntentionDescriptor;

public class ConditionalShape_Wrap_Intention implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;

  public ConditionalShape_Wrap_Intention() {
  }

  public String getConcept() {
    return "jetbrains.mps.editor.diagram.structure.IShape";
  }

  public String getPresentation() {
    return "ConditionalShape_Wrap";
  }

  public String getPersistentStateKey() {
    return "jetbrains.mps.editor.diagram.intentions.ConditionalShape_Wrap_Intention";
  }

  public String getLanguageFqName() {
    return "jetbrains.mps.editor.diagram";
  }

  public IntentionType getType() {
    return IntentionType.NORMAL;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    if (!(isApplicableToNode(node, editorContext))) {
      return false;
    }
    return true;
  }

  private boolean isApplicableToNode(final SNode node, final EditorContext editorContext) {
    return !(SNodeOperations.isInstanceOf(node, "jetbrains.mps.editor.diagram.structure.ConditionalShape"));
  }

  public SNodeReference getIntentionNodeReference() {
    return new SNodePointer("r:a830e6a8-cced-4210-9092-b2b30a124dc8(jetbrains.mps.editor.diagram.intentions)", "4254343767714458849");
  }

  public boolean isSurroundWith() {
    return false;
  }

  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new ConditionalShape_Wrap_Intention.IntentionImplementation());
    }
    return myCachedExecutable;
  }

  public class IntentionImplementation implements IntentionExecutable {
    public IntentionImplementation() {
    }

    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "Add Condition";
    }

    public void execute(final SNode node, final EditorContext editorContext) {
      SLinkOperations.setTarget(SNodeOperations.replaceWithNewChild(node, "jetbrains.mps.editor.diagram.structure.ConditionalShape"), "shape", node, true);
    }

    public IntentionDescriptor getDescriptor() {
      return ConditionalShape_Wrap_Intention.this;
    }
  }
}
