package jetbrains.mps.editor.diagram.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("4c1a9060-d860-4f5a-a6a8-c32983a11557(jetbrains.mps.editor.diagram)"), PersistenceFacade.getInstance().createModelReference("r:a830e6a8-cced-4210-9092-b2b30a124dc8(jetbrains.mps.editor.diagram.intentions)"));
  }

  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new ConditionalShape_Wrap_Intention());
  }
}
