package jetbrains.mps.editor._diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class AbstractArgument_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AbstractArgument_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor._diagram.structure.AbstractArgument";
  }
}
