package jetbrains.mps.editor._diagram.behavior;

/*Generated by MPS */


public class AttributedFigureReference_BehaviorDescriptor extends AbstractFigureReference_BehaviorDescriptor {
  public AttributedFigureReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor._diagram.structure.AttributedFigureReference";
  }
}
