package jetbrains.mps.editor._diagram.behavior;

/*Generated by MPS */


public class BLQueryArgument_BehaviorDescriptor extends AbstractFigureArgument_BehaviorDescriptor {
  public BLQueryArgument_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor._diagram.structure.BLQueryArgument";
  }
}
