package jetbrains.mps.editor._diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.editor.behavior.EditorCellModel_BehaviorDescriptor;

public class CellModel_DiagramNode_BehaviorDescriptor extends EditorCellModel_BehaviorDescriptor {
  public CellModel_DiagramNode_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor._diagram.structure.CellModel_DiagramNode";
  }
}
