package jetbrains.mps.editor._diagram.behavior;

/*Generated by MPS */


public class ConnectionEndBLQuery_BehaviorDescriptor extends ConnectionEnd_BehaviorDescriptor {
  public ConnectionEndBLQuery_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor._diagram.structure.ConnectionEndBLQuery";
  }
}
