package jetbrains.mps.editor._diagram.behavior;

/*Generated by MPS */


public class DiagramElementBLQuery_BehaviorDescriptor extends DiagramElement_BehaviorDescriptor {
  public DiagramElementBLQuery_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor._diagram.structure.DiagramElementBLQuery";
  }
}
