package jetbrains.mps.editor._diagram.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class ThisEditorNodeExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ThisEditorNodeExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.editor._diagram.structure.ThisEditorNodeExpression";
  }
}
