package jetbrains.mps.editor.diagram.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.lang.scopes.runtime.NamedElementsScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.SNodePointer;

public class ShapeParameterReference_Constraints extends BaseConstraintsDescriptor {
  public ShapeParameterReference_Constraints() {
    super("jetbrains.mps.editor.diagram.structure.ShapeParameterReference");
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("parameter", new BaseReferenceConstraintsDescriptor("parameter", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_kjpbvx_a0a0a0a0a1a0b0a1a1;
          }

          @Override
          public Scope createScope(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            return new NamedElementsScope(SLinkOperations.getTargets(SNodeOperations.getAncestor(_context.getContextNode(), "jetbrains.mps.editor.diagram.structure.ShapeDefinition", true, false), "parameters", true));
          }
        };
      }
    });
    return references;
  }

  private static SNodePointer breakingNode_kjpbvx_a0a0a0a0a1a0b0a1a1 = new SNodePointer("r:52332b22-3bbd-40bc-9855-cc730b5beaa9(jetbrains.mps.editor.diagram.constraints)", "3454709602156596764");
}
